# Generated by Django 2.2.4 on 2019-11-04 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20191006_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapa',
            name='address',
        ),
        migrations.RemoveField(
            model_name='mapa',
            name='geolocation',
        ),
    ]
