# Generated by Django 2.2.4 on 2019-11-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20191104_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ('updated',)},
        ),
    ]
